module.exports = {
  apps: [
    {
      name: 'ai-links-admin',
      script: 'pnpm',
      args: '--filter admin start',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: 'logs/admin-error.log',
      out_file: 'logs/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      ignore_watch: ['node_modules', 'logs', '.next', '.git'],
    },
    {
      name: 'ai-links-worker',
      script: 'pnpm',
      args: '--filter worker start',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        WORKER_CONCURRENCY: 5,
      },
      error_file: 'logs/worker-error.log',
      out_file: 'logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      ignore_watch: ['node_modules', 'logs', 'dist', '.git'],
    },
  ],
};
